### ISSUE TITLE
RFC: Behavior Driven Development

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/frontend-e2e-tests#24]
The way the tests are written now are good for the purpose, but I was thinking if we want to slowly change the way we write to a more BDD-like style. 
See https://codecept.io/bdd/#what-is-behavior-driven-development

Instead of using `I.click('gerade eben')`, `I.click('Speicher')` we would write `I.assertThatRevisionWasNewlyCreated()` `I.saveMyWork()`. 
Besides that we could use the syntax Given, When, Then.
Pros:
- more readability

Cons:
- more complexity in code

Note:
- another subject of discussion is if we want to change the syntax to use Gherkin (see link above), but let's discuss it after closing this RFC.

**Comment by Entkenntnis** [comment]
Hi Hugo, thank you for the RFC.

The primary goal of this repo is at the moment to make it as easy as possible to write tests - e.g. we haven't covered much of author features yet. I didn't want to overengineer the tests, so I choose the simplest approach - as tests grow we could definitively need some more abstractions.

You can start with https://github.com/serlo/frontend-e2e-tests/pull/23 and refactor it in the style of your choice (e.g. BDD). If you find a good balance for readability and complexity you can present it.

**Comment by hugotiburtino** [comment]
Thanks a lot for your detailed and empathic answer. 
The overengineering part is a very good argument as well as the idea of playing around in the beginnings of the repo.
Alright, I'll try it out a little bitte and let's see.
