### ISSUE TITLE
Set module type to ESM in https://github.com/serlo/frontend-e2e-tests

### ISSUE THREAD

**Issue by eliflores** [serlo/frontend-e2e-tests#41]

**Comment by Entkenntnis** [comment]
@eliflores It would be very cool if you could take this over

**Comment by eliflores** [comment]
Moving this issue back to the backlog, since the configuration required by Codeception needs to be in a CommonJS format - see comment [here](https://github.com/serlo/frontend-e2e-tests/pull/42#issue-1804942309).
