### ISSUE TITLE
yarn version

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend-e2e-tests#5]
@Entkenntnis this uses yarn v1, right?
Should we leave it there or also move to v3?

**Comment by Entkenntnis** [comment]
I'd like to keep the repo independent of the package manager. As far as I see we have no actual need to upgrade?

Are there any specific reasons you have in mind? Otherwise I'd like to keep it as it is.

**Comment by elbotho** [comment]
> I'd like to keep the repo independent of the package manager

when I use `yarn` on my machine it defaults to yarn3 and creates all the package commits etc. 
in #7 I fixed it to yarn1 but that is also not what you had in mind so I'm not sure what the best way is. Maybe I use npm for this one :)

**Comment by Entkenntnis** [comment]
@elbotho so I moved this repo back to npm :) - KISS

**Comment by Entkenntnis** [comment]
the new gitignore should allow parallel usage of yarn
